version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: always
  
  backend:
    image: renaissancejke/kittygram_backend:latest
    env_file: .env
    volumes:
      - static:/static
      - media:/app/media
    depends_on:
      - db
  
  frontend:
    image: renaissancejke/kittygram_frontend:latest
    env_file: .env
    command: cp -r /app/build/. /static/
    volumes:
      - static:/static
  
  gateway:
    image: renaissancejke/kittygram_gateway:latest
    env_file: .env
    volumes:
      - static:/static
      - media:/media
    depends_on:
      - backend
    ports:
      - 9000:80